### PR TITLE
DO NOT MERGE: testing prow

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@adrcunha thanks for all of your help here!

**Comment by adrcunha** [comment]
@aaron-prindle Now it's a good time to  mark tide and the presubmit tests as required checks.

**Comment by adrcunha** [comment]
Your unit tests are failing for legitimate reasons. You should be able to fix them, and once they pass locally there's no reason for them not passing on Prow.

**Comment by bobcatfish** [comment]
yessssssss

thanks @adrcunha !!!

**Pull request closed without merging**
