### PR TITLE
[WIP] [DO NOT MERGE] Only run fan-in fan-out test

### PR DESCRIPTION
**Pull request by bobcatfish**
Trying to gather more info for #375 - does the test fail when it's run
on it's own? (not 100% sure i got the syntax right haha just winging it)

+ @shashwathi @pivotal-nader-ziada @adrcunha

### CODE REVIEW

**Comment by bobcatfish** [comment]
Boo that didn't work:

```
I0109 19:37:14.793] === RUN   TestPipelineRun
I0109 19:37:14.793] --- PASS: TestPipelineRun (0.00s)
I0109 19:37:14.794] testing: warning: no tests to run
I0109 19:37:14.794] PASS
I0109 19:37:15.798] ok  	github.com/knative/build-pipeline/test	1.309s [no tests to run]
```

I'll try this locally before pushing again XD

**Comment by pivotal-nader-ziada** [comment]
the integration tests job looks like it passed, but it didn't actually run any tests

**Comment by bobcatfish** [comment]
Looks like it fails when it's run on it's own and the error I thought was ominous doesn't seem to be there:

https://gubernator.knative.dev/build/knative-prow/pr-logs/pull/knative_build-pipeline/377/pull-knative-build-pipeline-integration-tests/1083087926100758530/

This looks interesting tho:

```
I0109 20:04:48.199] ---
I0109 20:04:48.199] apiVersion: pipeline.knative.dev/v1alpha1
I0109 20:04:48.199] kind: TaskRun
I0109 20:04:48.199] metadata:
I0109 20:04:48.199]   creationTimestamp: "2019-01-09T19:54:48Z"
I0109 20:04:48.199]   generation: 1
I0109 20:04:48.199]   labels:
I0109 20:04:48.200]     pipeline.knative.dev/pipeline: helloworld-pipeline1
I0109 20:04:48.200]     pipeline.knative.dev/pipelineRun: helloworld-pipelinerun1
I0109 20:04:48.200]   name: helloworld-pipelinerun1-create-file-kritis
I0109 20:04:48.200]   namespace: arendelle-gniwfnkv
I0109 20:04:48.200]   ownerReferences:
I0109 20:04:48.200]   - apiVersion: pipeline.knative.dev/v1alpha1
I0109 20:04:48.200]     blockOwnerDeletion: true
I0109 20:04:48.200]     controller: true
I0109 20:04:48.201]     kind: PipelineRun
I0109 20:04:48.201]     name: helloworld-pipelinerun1
I0109 20:04:48.201]     uid: 6b32ed53-1448-11e9-9c86-42010a800104
I0109 20:04:48.201]   resourceVersion: "1505"
I0109 20:04:48.201]   selfLink: /apis/pipeline.knative.dev/v1alpha1/namespaces/arendelle-gniwfnkv/taskruns/helloworld-pipelinerun1-create-file-kritis
I0109 20:04:48.201]   uid: 6b3a19b4-1448-11e9-9c86-42010a800104
I0109 20:04:48.201] spec:
I0109 20:04:48.201]   generation: 1
I0109 20:04:48.201]   inputs:
I0109 20:04:48.201]     resources:
I0109 20:04:48.202]     - name: workspace
I0109 20:04:48.202]       paths: null
I0109 20:04:48.202]       resourceRef:
I0109 20:04:48.202]         name: kritis-resource-git
I0109 20:04:48.202]     - name: gcsbucket
I0109 20:04:48.202]       paths: null
I0109 20:04:48.202]       resourceRef:
I0109 20:04:48.202]         name: gcs-resource
I0109 20:04:48.202]   outputs:
I0109 20:04:48.202]     resources:
I0109 20:04:48.202]     - name: workspace
I0109 20:04:48.203]       paths:
I0109 20:04:48.203]       - /pvc/create-file-kritis/workspace
I0109 20:04:48.203]       resourceRef:
I0109 20:04:48.203]         name: kritis-resource-git
I0109 20:04:48.203]   taskRef:
I0109 20:04:48.203]     kind: Task
I0109 20:04:48.203]     name: create-file
I0109 20:04:48.203]   trigger:
I0109 20:04:48.203]     type: ""
I0109 20:04:48.203] status:
I0109 20:04:48.203]   conditions:
I0109 20:04:48.204]   - lastTransitionTime: "2019-01-09T19:54:58Z"
I0109 20:04:48.204]     message: 'pod status "PodScheduled":"False"; message: "0/3 nodes are available:
I0109 20:04:48.204]       3 node(s) had no available volume zone."'
I0109 20:04:48.204]     reason: Pending
I0109 20:04:48.204]     status: Unknown
I0109 20:04:48.204]     type: Succeeded
I0109 20:04:48.204]   podName: helloworld-pipelinerun1-create-file-kritis-pod-84e1d2
I0109 20:04:48.204]   startTime: "2019-01-09T19:54:48Z"
```

**Comment by shashwathi** [comment]
@bobcatfish : @pivotal-nader-ziada and I were suspecting if `no available volume zone` means that test is running across multiple zones and PVCs cannot be shared. 

- Why is it happening only in this test.
This test is the only with 4 tasks but test fails in running the first task itself so its not because of parallel accessing of PVC.
Uses GCS resource but for something to fail with execution pod should be initialized in first place.
There are other tests that run PipelineRun so it is not creation of PVCs.

**Comment by bobcatfish** [comment]
> This test is the only with 4 tasks but test fails in running the first task itself so its not because of parallel accessing of PVC.

I'll try reducing the test to only one task just to see if the failure still occurs!

**Comment by bobcatfish** [comment]
oooo looks like it still fails, which is interesting:

```
I0109 21:15:29.426]   taskRuns:
I0109 21:15:29.426]     helloworld-pipelinerun1-create-file-kritis:
I0109 21:15:29.426]       conditions:
I0109 21:15:29.427]       - lastTransitionTime: "2019-01-09T21:05:39Z"
I0109 21:15:29.427]         message: 'pod status "PodScheduled":"False"; message: "0/3 nodes are available:
I0109 21:15:29.427]           3 node(s) had no available volume zone."'
I0109 21:15:29.427]         reason: Pending
I0109 21:15:29.427]         status: Unknown
I0109 21:15:29.427]         type: Succeeded
I0109 21:15:29.427]       podName: helloworld-pipelinerun1-create-file-kritis-pod-442c92
I0109 21:15:29.427]       startTime: "2019-01-09T21:05:29Z"
```

**Comment by bobcatfish** [comment]
```
I0109 21:29:35.339] ERROR: (gcloud.container.get-server-config) One of [--zone, --region] must be supplied: Please specify location.
```
hm weird. well i think just changing it in one place probably isnt enough after looking at https://github.com/knative/test-infra/pull/297/commits/c237e7930abde38f75fb89430a4d4585af32661a

**Comment by bobcatfish** [comment]
Okay looks like it passed without the output! So that (i think) should imply that i can simplify this test down to _only_ having the output and it should fail...

**Comment by bobcatfish** [comment]
Okay I think I figured out what's going on, closing this PR and will update #375.

**Pull request closed without merging**
