### PR TITLE
Fix invalid error message for storage output resource

### PR DESCRIPTION
**Pull request by afrittoli**
The code branch is about storage output and not git.

### CODE REVIEW

**Comment by afrittoli** [comment]
I noticed this while reading the got, it confused me, so I though I might as well just fix it.

I'm not sure what's the community preference about tiny fixes, I usually try to keep PRs as small and self-contained as possible, so I keep this kind of fixes in their own commit. Please let me know if it's not appropriate.

**Comment by pivotal-nader-ziada** [comment]
Thanks @afrittoli for the fix

/ok-to-test

**Comment by bobcatfish** [comment]
Nice, really appreciate the attention to detail @afrittoli !! :heart:

**Pull request merged**
