### PR TITLE
Correcting usage link to point to using.md

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Comment by bobcatfish** [comment]
ooo nice, thanks @cagiti !! looks like you're going to need to sign the cla before we can merge this

/ok-to-test

(also note that #460 is completely removing `using.md` - but i should make sure to update `usage.md` to point at the right docs now 😅 )

**Comment by cagiti** [comment]
Hi @bobcatfish, I signed the CLASS after I pushed the PR... not sure whether it is able to check again? 😀

**Comment by pivotal-nader-ziada** [comment]
@cagiti looks like #460 resulted in a conflict for your PR, sorry about that. Would you mind resolving the conflict?

**Comment by bobcatfish** [comment]
I think this is actually fixed in the latest version of the tutorial docs - sorry about this @cagiti , I thought it got merged before I made my change :(

(now that you've got the CLA signed tho we'd love any more fixes you notice :pray: :smile: )

**Pull request closed without merging**
