### PR TITLE
Remove using.md & fix some links 😅

### PR DESCRIPTION
**Pull request by bobcatfish**
This doc was replaced in
https://github.com/knative/build-pipeline/commit/c579a789c3a2f3583ec4cf2fac420b3716c3c86f#diff-b70613b1372e1333b880f19677a70ef8
with files specific to each CRD type but it looks like
https://github.com/knative/build-pipeline/commit/9585e0d884915500ac534870e149f4472295003a#diff-b70613b1372e1333b880f19677a70ef8
accidentally re-added it

@pivotal-nader-ziada I think this might lose some doc changes you were trying to make in https://github.com/knative/build-pipeline/pull/463 which would need to happen in the specific docs for each type :innocent: :sweat_smile:

### CODE REVIEW

**Comment by abayer** [comment]
/lgtm
/meow box
(something tells me `/meow` may be down, though)

**Comment by bobcatfish** [comment]
> (something tells me `/meow` may be down, though)

HOW ARE WE SUPPOSED TO LIVE LIKE THIS @abayer

**Comment by abayer** [comment]
@bobcatfish I DON'T KNOW!

**Pull request merged**
