### PR TITLE
Add @vdemeester as an owner! 🙌

### PR DESCRIPTION
**Pull request by bobcatfish**
@vdemeester is one of our top four contributors! He has implemented
important features such as Task cancellation, he substantially improved
the maintainability of our tests with the addition of test builders,
and he's vigilant in taking on less glamourous work such as fixing up
docs to conform to the k8s style guide.

Not to mention almost every one of his commits has an emoji in it which,
in combination with his thoughtful and helpful review comments,
contributes to a welcoming and fun project atmosphere :D

celebrating cats

### CODE REVIEW

**Comment by bobcatfish** [comment]
/block

Let's merge #467 first.

**Comment by bobcatfish** [comment]
/hold
Let's merge #467 first.

**Comment by ImJasonH** [comment]
🥇🎉

/lgtm

**Pull request merged**
