### PR TITLE
Running dep ensure to add required dependencies.

### PR DESCRIPTION
**Pull request by tejal29**
Running dep ensure on master

In commit 2a03869, I ran `dep prune`
which did not respect the [[prune.projects]] and removed
"github.com/knative/test-infra"
Running dep ensure on master fixes this issue.

### CODE REVIEW

**Comment by bobcatfish** [comment]
Can you explain more about why `dep prune` removed things which were needed? Do we need to investigate that further?

/approve
/lgtm
/hold

(Remove /hold when ready with /hold cancel)

**Comment by tejal29** [comment]
yeah, its bizzare, 
Running `dep prune` says:
```
tejaldesai@tejaldesai~/go/src/github.com/knative/build-pipeline: (fix_hack)$ dep prune
Pruning is now performed automatically by dep ensure.
Set prune settings in Gopkg.toml and it it will be applied when running ensure.

This command currently still prunes as it always has, to ease the transition.
However, it will be removed in a future version of dep.

Now is the time to update your Gopkg.toml and remove `dep prune` from any scripts.
```
And then goes and deletes required files anyways
```
tejaldesai@tejaldesai~/go/src/github.com/knative/build-pipeline: (fix_hack)$ git status | grep 'test-infra'
	deleted:    vendor/github.com/knative/test-infra/scripts/README.md
	deleted:    vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
	deleted:    vendor/github.com/knative/test-infra/scripts/library.sh
	deleted:    vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
	deleted:    vendor/github.com/knative/test-infra/scripts/release.sh
	vendor/github.com/knative/test-infra/CONTRIBUTING.md
	vendor/github.com/knative/test-infra/LICENSE
	vendor/github.com/knative/test-infra/OWNERS
	vendor/github.com/knative/test-infra/README.md
	vendor/github.com/knative/test-infra/WORKSPACE
	vendor/github.com/knative/test-infra/dummy.go
```
I will take a look later.

**Comment by tejal29** [comment]
/remove hold
 `dep prune` is deprecated and avoided as per this thread
https://github.com/golang/dep/issues/1820#issuecomment-384807014

**Pull request merged**
