### PR TITLE
Update test-infra to include latest features of release.sh

### PR DESCRIPTION
**Pull request by adrcunha**
Major changes:
* use flags instead of environment variables for setting GCR/GCS
* log configuration at the start of the process
* be more verbose when tagging/publishing

### CODE REVIEW

**Comment by bobcatfish** [comment]
sorry for the delay @adrcunha !

/approve

It looks like there is a conflict now but at least you'll just need the `lgtm`

**Comment by adrcunha** [comment]
Thanks, @bobcatfish. Resolved the conflict.

**Pull request merged**
