### PR TITLE
vendor: update test-infra scripts

### PR DESCRIPTION
**Pull request by vbatts**
# Changes

addresses https://github.com/knative/build-pipeline/pull/560#issuecomment-468299685
cc @adrcunha @ImJasonH

### CODE REVIEW

**Comment by vbatts** [comment]
if you'd like, i can remove the `|| exit 1` as well

**Comment by vdemeester** [comment]
@vbatts let's do that :angel:

**Comment by vbatts** [comment]
@vdemeester done

**Comment by bobcatfish** [comment]
/lgtm

(i think, right @vdemeester ?? :sweat_smile: )

**Comment by vbatts** [comment]
unrelated to this PR particularly, but I reckon there will be steps to not depend on knative test-infra scripts?

**Pull request merged**
