### PR TITLE
Update broken link in pipeline tutorial doc

### PR DESCRIPTION
**Pull request by navidshaikh**
s/pipelines/pipeline

### CODE REVIEW

**Comment by vdemeester** [comment]
I wonder if we should change `Tasks` to `Task` or `Pipeline` to `Pipelines` instead… cc @bobcatfish :sweat_smile:

**Comment by navidshaikh** [comment]
> I wonder if we should change `Tasks` to `Task` or `Pipeline` to `Pipelines` instead

IMO, we should name it singular (as its mentioned in `kind`), `Task` and `Pipeline`.

**Comment by vdemeester** [comment]
@navidshaikh agreeing, let's do that then :hugs:

**Comment by bobcatfish** [comment]
/lgtm

thanks @navidshaikh !

**Pull request merged**
