### PR TITLE
Minor: fix mispelling  in pull request template

### PR DESCRIPTION
**Pull request by chmouel**
My spellcheck OCD kicked in while proposing my first change

## Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md) for more details._

## Release Notes

```release-note

```

### CODE REVIEW

**Comment by chmouel** [comment]
This was failed due of some markdownlint errors, i have fixed the one for the .github md files but there is plenty more all around the repos md which is probably better suited for another PR or as we go change,

**Comment by bobcatfish** [comment]
hm I'm surprised the linting wanted those headings to all be top level :thinking: 

Anyway thanks for the fixes @chmouel !! :heart: :D

**Pull request merged**
