### PR TITLE
refactor controllers to use reconciler

### LINKED ISSUE #71: Use knative/serving style controllers
## Expected Behavior

Our controllers should be written in the current preferred style, which is that used byhttps://github.com/knative/serving .

### Bonus

Write some docs on how to write controllers in this style (maybe in https://github.com/knative/pkg).

If we want ppl to write controllers in this style, we should document _how_ to do that. The only choice currently will be to reverse engineer the style from the examples in knative/serving, and without guidance can easily lead to cargo-culting.

## Actual Behavior

In #66 we removed `kubebuilder` and re-did our controllers so that they use the same style as https://github.com/knative/build. However in the review, @ImJasonH pointed out that the style in https://github.com/knative/serving is actually the latest and greatest, and @mattmoor pointed us at https://github.com/mattmoor/warm-image as an example.

## Additional Info
Spawned from #57

### PR DESCRIPTION
**Pull request by pivotal-nader-ziada**
fixes #71 

depends on #82 

## Proposed changes

 * add reconciler skeleton for `taskRun` controller
 * update controller cmd
 * add webhook skeleton 

/cc @bobcatfish @dprotaso @shashwathi

### CODE REVIEW

**Comment by pivotal-nader-ziada** [comment]
The tests are failing because it depends on PR #82 which is under review

**Comment by pivotal-nader-ziada** [comment]
Here is a diagram showing what I expect the flow to be 


buildpipeline


 * `Pipeline` and `Task` don't have a custom controller
 * `PipelineRun` and `TaskRun` have a reconcile loop
 * when a user applies a pipeline or a task, the object is stored, but its not run until a `PipelineRun` or `TaskRun` are created
 * The `TaskRun` creates and tracks a **Knative Build**

**Comment by bobcatfish** [comment]
Paired on this with @pivotal-nader-ziada and I'm excited about it!

/approve
/lgtm

Will talk to @aaron-prindle and @tejal29 before removing the hold tho, since this will cause some conflicts with their work.

**Comment by bobcatfish** [comment]
@aaron-prindle and @tejal29 said they are okay with going ahead with this!

/hold cancel

(@dlorenc this builds a foundation for adding the webhook based validation for #29 )

/meow space

**Comment by aaron-prindle** [comment]
this is awesome!

**Pull request merged**
