### PR TITLE
Format markdown

### PR DESCRIPTION
**Pull request by mattmoor-sockpuppet**
Produced via: `prettier --write --prose-wrap=always $(find -name '*.md' | grep -v vendor | grep -v .github)`

### CODE REVIEW

**Comment by mattmoor** [comment]
/assign @bobcatfish  

This is prose-wrap mostly.

**Comment by bobcatfish** [comment]
/approve
/lgtm

I don't mind approving this, but do you think it would make more sense if we agreed on what the standards are before enforcing them? I'm still not clear on what they are

Remove if you want to go ahead:
/hold

**Comment by mattmoor** [comment]
I thought I replied, I guess not!

@evankanderson has been urging folks to use `prettier.io` to get consistently formatted markdown (I think this was adopted when we migrated the original spec to markdown?).  I don't have strong opinions about it more than a desire for consistency.

I suppose that we can document the use of `prettier.io` somewhere, but my hope is that it will become roboticized code review suggestions as soon as Github lands multi-line suggestions.

**Pull request merged**
