### PR TITLE
Add 2019 Roadmap

### PR DESCRIPTION
**Pull request by ImJasonH**
This proposes an outline of our 2019 roadmap. Please leave comments and propose new items.

### CODE REVIEW

**Comment by abayer** [comment]
A few things I can think of that should probably be on the roadmap - sidecar containers for `Task`s, the ability to have a `Task` run on something other than a container (i.e., running on a Windows or Mac box somewhere), and the ability for a `Task` to pause until some condition it can poll for is met (to enable things like manual approval steps to be built on top of Build Pipeline).

**Comment by abayer** [comment]
@ImJasonH - fantastic, thanks!

**Comment by ImJasonH** [comment]
@bobcatfish Updated the link from CONTRIBUTING.md

**Comment by bobcatfish** [comment]
/lgtm

EXCITING!!

image

**Pull request merged**
