### PR TITLE
DO NOT MERGE: minimal task and taskrun controller impl

### PR DESCRIPTION
**Pull request by aaron-prindle**
This PR adds minimal controller logic to the task and taskrun controllers.  The task controller now creates taskruns and the taskrun controller creates builds. Additionally the config/200-clusterrole.yaml file was added to have knative cache access.

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Currently when Task/TaskRun CRDs are submitted, the controller syncHandler does not run.  Currently trying to figure out what the issue is there.

**Comment by pivotal-nader-ziada** [comment]
Why do we need a Task controller? Does the task automatically trigger a run once its created, doesn't the user or the pipeline have to trigger a taskRun?
I was assuming we would just need a PipelineRun and TaskRun controllers

**Comment by aaron-prindle** [comment]
It seems to be hanging waiting for caching forever here: https://github.com/knative/build-pipeline/blob/master/cmd/controller/main.go#L146

**Comment by aaron-prindle** [comment]
I had assumed that the method for manually triggering a TaskRun would be to create a Task with some "manual run" field set and the Task controller would then spawn a TaskRun in this case.

**Comment by pivotal-nader-ziada** [comment]
`TaskRun` has its own CRD with a [TriggerRef](https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/taskrun_types.go#L29) so you can just create a `TaskRun` and that should be the one creating a build and tracking it. The trigger [value](https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/taskrun_types.go#L52) can be `pipelineRun` or `Manual`

**Comment by aaron-prindle** [comment]
Ah I misunderstood this, thanks!  I will change the Task/TaskRun controller to reflect this.

**Pull request closed without merging**
