### PR TITLE
Remove infinite loop

### PR DESCRIPTION
**Pull request by shashwathi**
- Avoids getting `PipelineSpec` `SetDefaults()` into infinite loop

### CODE REVIEW

**Comment by bobcatfish** [comment]
A quick note for future commits, we want to try to [make sure commit messages include as much information as possible](https://github.com/knative/build-pipeline/blob/master/CONTRIBUTING.md#commit-messages), in this case it seems pretty self evident that this function was calling itself, however it would be interesting to understand more about how we got into that state (if we know!)

**Comment by shashwathi** [comment]
@bobcatfish : Updated commit msg with more details.

**Comment by bobcatfish** [comment]
> @bobcatfish : Updated commit msg with more details.

Thanks @shashwathi !! <3

**Pull request merged**
