### PR TITLE
added additional OWNERS file to test/ directory for prow

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by bobcatfish** [comment]
oh wait

**Comment by aaron-prindle** [comment]
does prow read from both dirs?

**Comment by bobcatfish** [comment]
> does prow read from both dirs?

afaik (@adrcunha correct me if im wrong) it's hierarchical, like an OWNERS file in a dir will override the level above it. in the knative/serving repo this was useful cuz different folks owned some of the test code

**Comment by adrcunha** [comment]
Yes, OWNERS file are hierarchical, just like in perforce.

**Pull request closed without merging**
